language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose --no-default-features
  - cargo build --verbose
  - cargo test --verbose
notifications:
  email: false
