[package]
name = "iri-string"
version = "0.1.1"
authors = ["YOSHIOKA Takuma <lo48576@hard-wi.red>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = "IRI as string"
repository = "https://github.com/lo48576/iri-string"
keywords = ["IRI", "URI"]

[features]
default = ["serde"]

[dependencies]
opaque_typedef = "^0.0.3"
opaque_typedef_macros = "^0.0.3"
serde = { version = "^1.0.45", optional = true, features = ["derive"] }
url = "^1.7"

[badges]
travis-ci = { repository = "lo48576/iri-string" }
